# pull official base image
FROM node:13.12.0-alpine
ENV NODE_ENV development
# set working directory
WORKDIR /frontend

# add `/frontend/node_modules/.bin` to $PATH
ENV PATH /frontend/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm ci
# RUN npm install react-scripts@3.4.1 -g --silent

# add frontend
COPY . ./

# start app
CMD ["npm", "start"]